### ISSUE TITLE
Task 0

### ISSUE THREAD

**Issue by arturpietrzak** [ArtJSON/PT#1]
## Task 0 checklist
- [X] the task provides required feedback and has been submitted (needs grading)
- [X] the ability to clone the repository to the teacher's computer
- [X] `README.md` contains required information
- [X] build succeeded
- [X] all UT's are green
